### ISSUE TITLE
Great

### ISSUE THREAD

**Issue by patrickharris** [FruitieX/hue-forwarder#3]
Hey - I just wanted to say this is a great project - fantastic idea. Did you work out what was causing the latency issue? Also I really like your idea in the philips dev forum of polling a single CLIPGenericStatus sensor that is updated by rules to watch multiple states. It makes polling much more feasible.

**Comment by FruitieX** [comment]
Hi, sorry for late reply :-)

Did not work out the cause for the latency issue, but it seemed to be caused by spotty wifi connection. Now I'm running the project on my home server over ethernet, and there have been no problems there.
